//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heiflow.Core {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heiflow.Core.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 # SFR: Stream-Flow Routing package file created on 2013/4/16 by ModelMuse version 2.17.1.0.
        ///REACHINPUT TRANSROUTE 
        ///TABFILES 12 4847
        /// 10676 389 0 0 8.640000000000E+004  1.000000000000E-002  9 58 2 5 1 30 0 1 24 0.9 2.5  IFACE # Data Set 1: NSTRM NSS NSFRPAR NPARSEG CONST DLEAK ISTCB1  ISTCB2 ISFROPT NSTRAIL ISUZN NSFRSETS IRTFLG NUMTIM WEIGHT FLWTOL 的本地化字符串。
        /// </summary>
        internal static string SFRHead {
            get {
                return ResourceManager.GetString("SFRHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 389 0 0 # Data Set 5, Stress period 1: ITMP IRDFLG IPTFLG
        /// 1 1 6 0 0  0  0  0  0.03  # Data Set 6a: NSEG ICALC OUTSEG IUPSEG FLOW RUNOFF ETSW PPTSW ROUGHCH
        /// 50  # Data set 6b: WIDTH1
        /// 50  # Data set 6c: WIDTH2
        /// 2 1 6 0 0  0  0  0  0.03  # Data Set 6a: NSEG ICALC OUTSEG IUPSEG FLOW RUNOFF ETSW PPTSW ROUGHCH
        /// 50  # Data set 6b: WIDTH1
        /// 50  # Data set 6c: WIDTH2
        /// 3 1 0 0 0  0  0  0  0.03  # Data Set 6a: NSEG ICALC OUTSEG IUPSEG FLOW RUNOFF ETSW PPTSW ROUGHCH
        /// 50  # Data set 6b: WIDTH1
        /// 50  # Data set  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SFRSections {
            get {
                return ResourceManager.GetString("SFRSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [TITLE]
        ///HRB
        ///
        ///[OPTIONS]
        ///FLOW_UNITS           CMS
        ///INFILTRATION         HORTON
        ///FLOW_ROUTING         KINWAVE
        ///START_DATE           01/01/2000
        ///START_TIME           00:00:00
        ///REPORT_START_DATE    01/01/2000
        ///REPORT_START_TIME    00:00:00
        ///END_DATE             12/31/2000
        ///END_TIME             00:00:00
        ///SWEEP_START          01/01
        ///SWEEP_END            12/31
        ///DRY_DAYS             0
        ///REPORT_STEP          24:00:00
        ///WET_STEP             24:00:00
        ///DRY_STEP             24:00:00
        ///ROUTING_STEP         24:00:00 
        ///ALL [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SWMMSections {
            get {
                return ResourceManager.GetString("SWMMSections", resourceCulture);
            }
        }
    }
}
