//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heiflow.Plugins.Default.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heiflow.Plugins.Default.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Active Datasets 的本地化字符串。
        /// </summary>
        internal static string Active_Datasets {
            get {
                return ResourceManager.GetString("Active_Datasets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plot active data set time series 的本地化字符串。
        /// </summary>
        internal static string Active_Datasets_tips {
            get {
                return ResourceManager.GetString("Active_Datasets_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analysis 的本地化字符串。
        /// </summary>
        internal static string Analysis_group {
            get {
                return ResourceManager.GetString("Analysis_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Animation 的本地化字符串。
        /// </summary>
        internal static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Budget Analysis 的本地化字符串。
        /// </summary>
        internal static string Budget_Analysis {
            get {
                return ResourceManager.GetString("Budget_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cascade 的本地化字符串。
        /// </summary>
        internal static string Cascade {
            get {
                return ResourceManager.GetString("Cascade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Common 的本地化字符串。
        /// </summary>
        internal static string Common_Group {
            get {
                return ResourceManager.GetString("Common_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Grid From Modflow File 的本地化字符串。
        /// </summary>
        internal static string CreateGridFromMF {
            get {
                return ResourceManager.GetString("CreateGridFromMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 current layer 的本地化字符串。
        /// </summary>
        internal static string current_layer {
            get {
                return ResourceManager.GetString("current_layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Cube Editor 的本地化字符串。
        /// </summary>
        internal static string Data_Cube_Editor {
            get {
                return ResourceManager.GetString("Data_Cube_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Data Cube Editor 的本地化字符串。
        /// </summary>
        internal static string Data_Cube_Editor_tips {
            get {
                return ResourceManager.GetString("Data_Cube_Editor_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data 的本地化字符串。
        /// </summary>
        internal static string Data_Group {
            get {
                return ResourceManager.GetString("Data_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database 的本地化字符串。
        /// </summary>
        internal static string Database_Panel {
            get {
                return ResourceManager.GetString("Database_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driving Forces 的本地化字符串。
        /// </summary>
        internal static string Driving_Forces_group {
            get {
                return ResourceManager.GetString("Driving_Forces_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extensions 的本地化字符串。
        /// </summary>
        internal static string Extensions_root {
            get {
                return ResourceManager.GetString("Extensions_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        internal static string File_root {
            get {
                return ResourceManager.GetString("File_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finite Difference Grid 的本地化字符串。
        /// </summary>
        internal static string Finite_Difference_Grid {
            get {
                return ResourceManager.GetString("Finite_Difference_Grid", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   查找类似 Global 的本地化字符串。
        /// </summary>
        internal static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grid 的本地化字符串。
        /// </summary>
        internal static string Grid_group {
            get {
                return ResourceManager.GetString("Grid_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layer Group 的本地化字符串。
        /// </summary>
        internal static string Layer_Group {
            get {
                return ResourceManager.GetString("Layer_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legend 的本地化字符串。
        /// </summary>
        internal static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map Window 的本地化字符串。
        /// </summary>
        internal static string Map_control {
            get {
                return ResourceManager.GetString("Map_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map 的本地化字符串。
        /// </summary>
        internal static string Map_Group {
            get {
                return ResourceManager.GetString("Map_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model 的本地化字符串。
        /// </summary>
        internal static string Model_Group {
            get {
                return ResourceManager.GetString("Model_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model 的本地化字符串。
        /// </summary>
        internal static string Model_root {
            get {
                return ResourceManager.GetString("Model_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Running 的本地化字符串。
        /// </summary>
        internal static string Model_Running {
            get {
                return ResourceManager.GetString("Model_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Time 的本地化字符串。
        /// </summary>
        internal static string Model_Time {
            get {
                return ResourceManager.GetString("Model_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Toolbox 的本地化字符串。
        /// </summary>
        internal static string Model_Toolbox {
            get {
                return ResourceManager.GetString("Model_Toolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Model Toolbox 的本地化字符串。
        /// </summary>
        internal static string Model_Toolbox_tips {
            get {
                return ResourceManager.GetString("Model_Toolbox_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Tool 的本地化字符串。
        /// </summary>
        internal static string ModelTool_Group {
            get {
                return ResourceManager.GetString("ModelTool_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MT3DMS 的本地化字符串。
        /// </summary>
        internal static string MT3DMS {
            get {
                return ResourceManager.GetString("MT3DMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ODM Database 的本地化字符串。
        /// </summary>
        internal static string ODM_Database {
            get {
                return ResourceManager.GetString("ODM_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show ODM Database Explorer 的本地化字符串。
        /// </summary>
        internal static string ODM_Database_Tips {
            get {
                return ResourceManager.GetString("ODM_Database_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter Mapping Tool 的本地化字符串。
        /// </summary>
        internal static string Parameter_Mapping_Tool {
            get {
                return ResourceManager.GetString("Parameter_Mapping_Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Profile Viewer 的本地化字符串。
        /// </summary>
        internal static string Profile_Viewer {
            get {
                return ResourceManager.GetString("Profile_Viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progress Window 的本地化字符串。
        /// </summary>
        internal static string ProgressWindow {
            get {
                return ResourceManager.GetString("ProgressWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Explorer 的本地化字符串。
        /// </summary>
        internal static string Project_Explorer {
            get {
                return ResourceManager.GetString("Project_Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project 的本地化字符串。
        /// </summary>
        internal static string Project_panel {
            get {
                return ResourceManager.GetString("Project_panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property 的本地化字符串。
        /// </summary>
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running 的本地化字符串。
        /// </summary>
        internal static string Running_group {
            get {
                return ResourceManager.GetString("Running_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Species 的本地化字符串。
        /// </summary>
        internal static string Set_Species {
            get {
                return ResourceManager.GetString("Set_Species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        internal static string Setting_group {
            get {
                return ResourceManager.GetString("Setting_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spatial Tools 的本地化字符串。
        /// </summary>
        internal static string Spatial_Tools {
            get {
                return ResourceManager.GetString("Spatial_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Spatial Tools 的本地化字符串。
        /// </summary>
        internal static string Spatial_Tools_tips {
            get {
                return ResourceManager.GetString("Spatial_Tools_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Surface Parameter 的本地化字符串。
        /// </summary>
        internal static string Surface_Parameter {
            get {
                return ResourceManager.GetString("Surface_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table View 的本地化字符串。
        /// </summary>
        internal static string Table_View {
            get {
                return ResourceManager.GetString("Table_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Table View 的本地化字符串。
        /// </summary>
        internal static string Table_View_tips {
            get {
                return ResourceManager.GetString("Table_View_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Terrain Viewer 的本地化字符串。
        /// </summary>
        internal static string Terrain_Viewer {
            get {
                return ResourceManager.GetString("Terrain_Viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Terrain Viewer 的本地化字符串。
        /// </summary>
        internal static string Terrain_Viewer_tips {
            get {
                return ResourceManager.GetString("Terrain_Viewer_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        internal static string Time_group {
            get {
                return ResourceManager.GetString("Time_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tool 的本地化字符串。
        /// </summary>
        internal static string Tool_group {
            get {
                return ResourceManager.GetString("Tool_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertical Profile Viewer 的本地化字符串。
        /// </summary>
        internal static string Vertical_Profile_Viewer {
            get {
                return ResourceManager.GetString("Vertical_Profile_Viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Vertical Profile Viewer 的本地化字符串。
        /// </summary>
        internal static string Vertical_Profile_Viewer_tips {
            get {
                return ResourceManager.GetString("Vertical_Profile_Viewer_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3D View 的本地化字符串。
        /// </summary>
        internal static string View_3d {
            get {
                return ResourceManager.GetString("View_3d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show 3D View 的本地化字符串。
        /// </summary>
        internal static string View_3d_tips {
            get {
                return ResourceManager.GetString("View_3d_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        internal static string View_root {
            get {
                return ResourceManager.GetString("View_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weather Generator 的本地化字符串。
        /// </summary>
        internal static string Weather_Generator {
            get {
                return ResourceManager.GetString("Weather_Generator", resourceCulture);
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiAnimation16 {
            get {
                object obj = ResourceManager.GetObject("UiAnimation16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiAnimation24 {
            get {
                object obj = ResourceManager.GetObject("UiAnimation24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiAnimation32 {
            get {
                object obj = ResourceManager.GetObject("UiAnimation32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiBalance16 {
            get {
                object obj = ResourceManager.GetObject("UiBalance16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiBalance24 {
            get {
                object obj = ResourceManager.GetObject("UiBalance24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiBalance32 {
            get {
                object obj = ResourceManager.GetObject("UiBalance32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiChart16 {
            get {
                object obj = ResourceManager.GetObject("UiChart16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiChart24 {
            get {
                object obj = ResourceManager.GetObject("UiChart24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiChart32 {
            get {
                object obj = ResourceManager.GetObject("UiChart32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiCube16 {
            get {
                object obj = ResourceManager.GetObject("UiCube16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiCube24 {
            get {
                object obj = ResourceManager.GetObject("UiCube24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiCube32 {
            get {
                object obj = ResourceManager.GetObject("UiCube32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiDatabase16 {
            get {
                object obj = ResourceManager.GetObject("UiDatabase16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiDatabase24 {
            get {
                object obj = ResourceManager.GetObject("UiDatabase24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiDatabase32 {
            get {
                object obj = ResourceManager.GetObject("UiDatabase32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiDefault16 {
            get {
                object obj = ResourceManager.GetObject("UiDefault16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiDefault24 {
            get {
                object obj = ResourceManager.GetObject("UiDefault24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiDefault32 {
            get {
                object obj = ResourceManager.GetObject("UiDefault32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiGrid16 {
            get {
                object obj = ResourceManager.GetObject("UiGrid16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiGrid24 {
            get {
                object obj = ResourceManager.GetObject("UiGrid24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiGrid32 {
            get {
                object obj = ResourceManager.GetObject("UiGrid32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiLayer16 {
            get {
                object obj = ResourceManager.GetObject("UiLayer16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiLayer24 {
            get {
                object obj = ResourceManager.GetObject("UiLayer24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiLayer32 {
            get {
                object obj = ResourceManager.GetObject("UiLayer32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiLegend16 {
            get {
                object obj = ResourceManager.GetObject("UiLegend16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiLegend24 {
            get {
                object obj = ResourceManager.GetObject("UiLegend24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiLegend32 {
            get {
                object obj = ResourceManager.GetObject("UiLegend32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiLink16 {
            get {
                object obj = ResourceManager.GetObject("UiLink16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiLink24 {
            get {
                object obj = ResourceManager.GetObject("UiLink24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiLink32 {
            get {
                object obj = ResourceManager.GetObject("UiLink32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiList16 {
            get {
                object obj = ResourceManager.GetObject("UiList16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiList24 {
            get {
                object obj = ResourceManager.GetObject("UiList24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiList32 {
            get {
                object obj = ResourceManager.GetObject("UiList32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiMap16 {
            get {
                object obj = ResourceManager.GetObject("UiMap16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiMap24 {
            get {
                object obj = ResourceManager.GetObject("UiMap24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiMap32 {
            get {
                object obj = ResourceManager.GetObject("UiMap32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiNetwork16 {
            get {
                object obj = ResourceManager.GetObject("UiNetwork16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiNetwork24 {
            get {
                object obj = ResourceManager.GetObject("UiNetwork24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiNetwork32 {
            get {
                object obj = ResourceManager.GetObject("UiNetwork32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiProfile16 {
            get {
                object obj = ResourceManager.GetObject("UiProfile16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiProfile24 {
            get {
                object obj = ResourceManager.GetObject("UiProfile24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiProfile32 {
            get {
                object obj = ResourceManager.GetObject("UiProfile32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiProgress16 {
            get {
                object obj = ResourceManager.GetObject("UiProgress16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiProgress24 {
            get {
                object obj = ResourceManager.GetObject("UiProgress24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiProgress32 {
            get {
                object obj = ResourceManager.GetObject("UiProgress32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiProperty16 {
            get {
                object obj = ResourceManager.GetObject("UiProperty16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiProperty24 {
            get {
                object obj = ResourceManager.GetObject("UiProperty24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiProperty32 {
            get {
                object obj = ResourceManager.GetObject("UiProperty32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiRun16 {
            get {
                object obj = ResourceManager.GetObject("UiRun16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiRun24 {
            get {
                object obj = ResourceManager.GetObject("UiRun24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiRun32 {
            get {
                object obj = ResourceManager.GetObject("UiRun32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiSettings16 {
            get {
                object obj = ResourceManager.GetObject("UiSettings16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiSettings24 {
            get {
                object obj = ResourceManager.GetObject("UiSettings24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiSettings32 {
            get {
                object obj = ResourceManager.GetObject("UiSettings32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiSpecies16 {
            get {
                object obj = ResourceManager.GetObject("UiSpecies16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiSpecies24 {
            get {
                object obj = ResourceManager.GetObject("UiSpecies24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiSpecies32 {
            get {
                object obj = ResourceManager.GetObject("UiSpecies32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiStats16 {
            get {
                object obj = ResourceManager.GetObject("UiStats16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiStats24 {
            get {
                object obj = ResourceManager.GetObject("UiStats24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiStats32 {
            get {
                object obj = ResourceManager.GetObject("UiStats32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiStop16 {
            get {
                object obj = ResourceManager.GetObject("UiStop16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiStop24 {
            get {
                object obj = ResourceManager.GetObject("UiStop24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiStop32 {
            get {
                object obj = ResourceManager.GetObject("UiStop32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiTable16 {
            get {
                object obj = ResourceManager.GetObject("UiTable16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiTable24 {
            get {
                object obj = ResourceManager.GetObject("UiTable24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiTable32 {
            get {
                object obj = ResourceManager.GetObject("UiTable32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiTerrain16 {
            get {
                object obj = ResourceManager.GetObject("UiTerrain16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiTerrain24 {
            get {
                object obj = ResourceManager.GetObject("UiTerrain24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiTerrain32 {
            get {
                object obj = ResourceManager.GetObject("UiTerrain32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiTime16 {
            get {
                object obj = ResourceManager.GetObject("UiTime16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiTime24 {
            get {
                object obj = ResourceManager.GetObject("UiTime24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiTime32 {
            get {
                object obj = ResourceManager.GetObject("UiTime32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiWeather16 {
            get {
                object obj = ResourceManager.GetObject("UiWeather16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiWeather24 {
            get {
                object obj = ResourceManager.GetObject("UiWeather24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiWeather32 {
            get {
                object obj = ResourceManager.GetObject("UiWeather32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
