//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heiflow.Models.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heiflow.Models.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Basic 的本地化字符串。
        /// </summary>
        internal static string BasicCategory {
            get {
                return ResourceManager.GetString("BasicCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Groundwater Flow 的本地化字符串。
        /// </summary>
        internal static string FlowCategory {
            get {
                return ResourceManager.GetString("FlowCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified Flux Boundaries 的本地化字符串。
        /// </summary>
        internal static string FluxCategory {
            get {
                return ResourceManager.GetString("FluxCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified Head Boundaries 的本地化字符串。
        /// </summary>
        internal static string HeadCategory {
            get {
                return ResourceManager.GetString("HeadCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Head-Dependent Flux Boundaries 的本地化字符串。
        /// </summary>
        internal static string HeadDependentCategory {
            get {
                return ResourceManager.GetString("HeadDependentCategory", resourceCulture);
            }
        }
        
        
        
        
        /// <summary>
        ///   查找类似 Outputs 的本地化字符串。
        /// </summary>
        internal static string ModelOutput {
            get {
                return ResourceManager.GetString("ModelOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multicomponent Transport 的本地化字符串。
        /// </summary>
        internal static string MT3DCategory {
            get {
                return ResourceManager.GetString("MT3DCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Observations 的本地化字符串。
        /// </summary>
        internal static string ObsCategory {
            get {
                return ResourceManager.GetString("ObsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output 的本地化字符串。
        /// </summary>
        internal static string OutputCategory {
            get {
                return ResourceManager.GetString("OutputCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output Control 的本地化字符串。
        /// </summary>
        internal static string OutputControlCategory {
            get {
                return ResourceManager.GetString("OutputControlCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chemical Reaction 的本地化字符串。
        /// </summary>
        internal static string PHTCategory {
            get {
                return ResourceManager.GetString("PHTCategory", resourceCulture);
            }
        }
        
        
        
        
        
        
        /// <summary>
        ///   查找类似 Variable-Density Flow 的本地化字符串。
        /// </summary>
        internal static string SEAWATCategory {
            get {
                return ResourceManager.GetString("SEAWATCategory", resourceCulture);
            }
        }
        
        
        
        /// <summary>
        ///   查找类似 Solver 的本地化字符串。
        /// </summary>
        internal static string SolverCategory {
            get {
                return ResourceManager.GetString("SolverCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subsidence 的本地化字符串。
        /// </summary>
        internal static string SubsidenceCategory {
            get {
                return ResourceManager.GetString("SubsidenceCategory", resourceCulture);
            }
        }
        
        
        

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiCompare16 {
            get {
                object obj = ResourceManager.GetObject("UiCompare16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiCompare24 {
            get {
                object obj = ResourceManager.GetObject("UiCompare24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiCompare32 {
            get {
                object obj = ResourceManager.GetObject("UiCompare32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiCube16 {
            get {
                object obj = ResourceManager.GetObject("UiCube16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiCube24 {
            get {
                object obj = ResourceManager.GetObject("UiCube24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiCube32 {
            get {
                object obj = ResourceManager.GetObject("UiCube32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiMap16 {
            get {
                object obj = ResourceManager.GetObject("UiMap16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiMap24 {
            get {
                object obj = ResourceManager.GetObject("UiMap24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiMap32 {
            get {
                object obj = ResourceManager.GetObject("UiMap32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiRaster16 {
            get {
                object obj = ResourceManager.GetObject("UiRaster16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiRaster24 {
            get {
                object obj = ResourceManager.GetObject("UiRaster24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiRaster32 {
            get {
                object obj = ResourceManager.GetObject("UiRaster32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiService16 {
            get {
                object obj = ResourceManager.GetObject("UiService16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiService24 {
            get {
                object obj = ResourceManager.GetObject("UiService24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiService32 {
            get {
                object obj = ResourceManager.GetObject("UiService32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiTable16 {
            get {
                object obj = ResourceManager.GetObject("UiTable16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiTable24 {
            get {
                object obj = ResourceManager.GetObject("UiTable24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UiTable32 {
            get {
                object obj = ResourceManager.GetObject("UiTable32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
