using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Heiflow.Models.Surface.Carbon
{
    public class CarbonPackageInputFiles
    {
        public CarbonPackageInputFiles()
        {
            FertC = 4.0;
        }

        public double FertC { get; set; }

        public void New(string configpath, string wq_input_path, int nhru, int nseg, int nreach, DateTime startDate, DateTime endDate)
        {
            int total_days = (endDate - startDate).Days + 1;
            int nyear = endDate.Year - startDate.Year + 1;

            SaveNPS_C(configpath, wq_input_path, nyear);
            SaveFertC(wq_input_path);
            save_sfrwq(configpath, wq_input_path, nseg, nreach);
            save_sfrwq_ps(wq_input_path, total_days);
        
        }

        private void SaveFertC(string wq_input_path)
        {
            var fert_times = 3;
            var fert_hru = 5;
            var fertc= Path.Combine(wq_input_path, "ferti_c.txt");
            StreamWriter sw_fertc = new StreamWriter(fertc);
            var line = string.Format("#fertilizer C file (kg/ha), according to num_fert_count and num_fert_cell in nps.ex. Generated by VHF on {0}", DateTime.Now);
            sw_fertc.WriteLine(line);
            double[] arr = Enumerable.Repeat(FertC, fert_hru).ToArray();
            var arr_str = string.Join(" ", arr);
            for (int i = 0; i < fert_times; i++)
            {
                sw_fertc.WriteLine(arr_str);
            }
            sw_fertc.Close();
        }

        private void SaveNPS_C(string configpath, string wq_input_path, int nyear)
        {
            var npsex = Path.Combine(configpath, "template\\nps_c.ex");
            var npsex_out = Path.Combine(wq_input_path, "nps_c.ex");
            StreamReader sr = new StreamReader(npsex);
            StreamWriter sw = new StreamWriter(npsex_out);
            string line;
            var riverph = new double[nyear];
            for (int i = 0; i < nyear; i++)
            {
                riverph[i] = 0.0;
            }
            for (int i = 0; i < 58; i++)
            {
                line = sr.ReadLine();
                sw.WriteLine(line);
            }
            line = string.Format("{0}   #river_pH_flag  0 is no revision (one data), 1 is constant rivision (one data), {0} is annual rivision for {0} years ({0} data)", nyear);
            sw.WriteLine(line);
            line = string.Join(" ", riverph) + " #river water pH revision  0 means no revision";
            sw.WriteLine(line);
            for (int i = 0; i < 22; i++)
            {
                line = sr.ReadLine();
                sw.WriteLine(line);
            }

            sr.Close();
            sw.Close();
        }
 
 
 
        private void save_sfrwq(string configpath, string wq_input_path, int nseg, int nreach)
        {
            StreamReader sr = new StreamReader(Path.Combine(configpath, "template\\sfrwq_carbon.ex"));
            StreamWriter sw = new StreamWriter(Path.Combine(wq_input_path, "sfrwq.ex"));
            var line = sr.ReadLine();
            var newline = string.Format("24 {0} {1}	1	5 # npolut, numreach, numseg, output_polut_index1,output_polut_index2", nreach, nseg);
            sw.WriteLine(newline);
            while (!sr.EndOfStream)
            {
                line = sr.ReadLine();
                sw.WriteLine(line);
            }

            sr.Close();
            sw.Close();
        }


        private void save_sfrwq_ps(string wq_input_path, int total_days)
        {
            StreamWriter sw = new StreamWriter(Path.Combine(wq_input_path, "sfrwq_ps.ex"));
            sw.WriteLine("1 2 # num_nps, ts_flag(1: constant; 2: time-varient)");
            sw.WriteLine("1 1 1 # iseg ireach reach_serial_id");
            sw.WriteLine("0 1 # time_step data_flag");
            sw.WriteLine("0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 # ps_q, NH₄, NO₃, PO₄, DOC1,DOC2,DOC3, DON1,DON2,DON3, Chl-a1,Chl-a2,Chl-a3, DIC, SOC, SON, SOP, PO₄_minP, PHYT, Sed, DO, Temp, pH, PHYTN, PHYTP");
            for (int i = 1; i <= total_days; i++)
            {
                sw.WriteLine(string.Format("{0} {1} # time_step data_flag", i, -1));
            }
            sw.Close();
        }

    }
}
