using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace Heiflow.Models.Surface.Carbon
{
    public class CarbonPackageInputFiles
    {
        public CarbonPackageInputFiles()
        {
            FertC = 4.0;
        }

        public double FertC { get; set; }

        public void New(string configpath, string wq_input_path, int nhru, int nseg, int nreach, DateTime startDate, DateTime endDate)
        {
            int total_days = (endDate - startDate).Days + 1;
            int nyear = endDate.Year - startDate.Year + 1;

            ModifyNPS(configpath, wq_input_path);
            SaveNPS_C(configpath, wq_input_path, nyear);
            SaveFertC(wq_input_path);
            save_sfrwq(configpath, wq_input_path, nseg, nreach);
            save_sfrwq_ps(wq_input_path, total_days);

        }

        private void SaveFertC(string wq_input_path)
        {
            var fert_times = 3;
            var fert_hru = 5;
            var fertc = Path.Combine(wq_input_path, "ferti_c.txt");
            StreamWriter sw_fertc = new StreamWriter(fertc);
            var line = string.Format("#fertilizer C file (kg/ha), according to num_fert_count and num_fert_cell in nps.ex. Generated by VHF on {0}", DateTime.Now);
            sw_fertc.WriteLine(line);
            double[] arr = Enumerable.Repeat(FertC, fert_hru).ToArray();
            var arr_str = string.Join(" ", arr);
            for (int i = 0; i < fert_times; i++)
            {
                sw_fertc.WriteLine(arr_str);
            }
            sw_fertc.Close();
        }

        private void SaveNPS_C(string configpath, string wq_input_path, int nyear)
        {
            var npsex = Path.Combine(configpath, "template\\nps_c.ex");
            var npsex_out = Path.Combine(wq_input_path, "nps_c.ex");
            StreamReader sr = new StreamReader(npsex);
            StreamWriter sw = new StreamWriter(npsex_out);
            string line;
            var riverph = new double[nyear];
            for (int i = 0; i < nyear; i++)
            {
                riverph[i] = 0.0;
            }
            for (int i = 0; i < 58; i++)
            {
                line = sr.ReadLine();
                sw.WriteLine(line);
            }

            line = string.Format("{0}   #river_pH_flag  0 is no revision (one data), 1 is constant rivision (one data), {0} is annual rivision for {0} years ({0} data)", nyear);
            sw.WriteLine(line);
            line = string.Join(" ", riverph) + " #river water pH revision  0 means no revision";
            sw.WriteLine(line);

            line = sr.ReadLine();
            line = sr.ReadLine();
            for (int i = 0; i < 22; i++)
            {
                line = sr.ReadLine();
                sw.WriteLine(line);
            }

            sr.Close();
            sw.Close();
        }

        private void save_sfrwq(string configpath, string wq_input_path, int nseg, int nreach)
        {
            StreamReader sr = new StreamReader(Path.Combine(configpath, "template\\sfrwq_carbon.ex"));
            StreamWriter sw = new StreamWriter(Path.Combine(wq_input_path, "sfrwq.ex"));
            var line = sr.ReadLine();
            var newline = string.Format("24 {0} {1}	1	5 # npolut, numreach, numseg, output_polut_index1,output_polut_index2", nreach, nseg);
            sw.WriteLine(newline);
            while (!sr.EndOfStream)
            {
                line = sr.ReadLine();
                sw.WriteLine(line);
            }

            sr.Close();
            sw.Close();
        }


        private void save_sfrwq_ps(string wq_input_path, int total_days)
        {
            StreamWriter sw = new StreamWriter(Path.Combine(wq_input_path, "sfrwq_ps.ex"));
            sw.WriteLine("1 2 # num_nps, ts_flag(1: constant; 2: time-varient)");
            sw.WriteLine("1 1 1 # iseg ireach reach_serial_id");
            sw.WriteLine("0 1 # time_step data_flag");
            sw.WriteLine("0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 # ps_q, NH₄, NO₃, PO₄, DOC1,DOC2,DOC3, DON1,DON2,DON3, Chl-a1,Chl-a2,Chl-a3, DIC, SOC, SON, SOP, PO₄_minP, PHYT, Sed, DO, Temp, pH, PHYTN, PHYTP");
            for (int i = 1; i <= total_days; i++)
            {
                sw.WriteLine(string.Format("{0} {1} # time_step data_flag", i, -1));
            }
            sw.Close();
        }

        private void ModifyNPS(string configpath, string wq_input_path)
        {
            var filePath = Path.Combine(wq_input_path, "nps.ex");
            try
            {
                // 读取所有行
                string[] lines = File.ReadAllLines(filePath);

                if (lines.Length == 0)
                {
                    Console.WriteLine("文件为空，无需处理。");
                    return;
                }

                // 处理第一行
                string firstLine = lines[0];
                string modifiedFirstLine = ModifyFertFlag(firstLine);

                // 如果内容有变化，则更新数组并写回文件
                if (modifiedFirstLine != firstLine)
                {
                    lines[0] = modifiedFirstLine;
                    File.WriteAllLines(filePath, lines);
                    Console.WriteLine("修改完成！");
                }
                else
                {
                    Console.WriteLine("第一行的第二个数字不符合修改条件（不为1），未作更改。");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("发生错误：" + ex.Message);
            }
        }

        /// <summary>
        /// 修改一行中第二个数字：若为"1"则改为"0"，否则保持原样。
        /// </summary>
        private string ModifyFertFlag(string line)
        {
            // 分离主数据和注释部分（以'#'为界）
            int commentIndex = line.IndexOf('#');
            string mainPart = commentIndex >= 0 ? line.Substring(0, commentIndex) : line;
            string commentPart = commentIndex >= 0 ? line.Substring(commentIndex) : "";

            // 匹配主数据中的所有连续数字
            MatchCollection matches = Regex.Matches(mainPart, @"\d+");
            if (matches.Count >= 2)
            {
                Match secondMatch = matches[1];
                string secondNumberStr = secondMatch.Value;

                // 仅当第二个数字等于 "1" 时才替换为 "0"
                if (secondNumberStr == "1")
                {
                    mainPart = mainPart.Remove(secondMatch.Index, secondMatch.Length)
                                      .Insert(secondMatch.Index, "0");
                }
            }

            return mainPart + commentPart;
        }

    }
}
