using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using Heiflow.Core.Data;

namespace Heiflow.Models.Surface.WaterQuality
{
    public class WQFiles
    {
        public WQFiles()
        {
            FertN = 10;
            FertP = 5;
            GW_Init_NO3 = 0.5f;
        }

        public float FertN { get; set; }

        public float FertP { get; set; }

        public float GW_Init_NO3 { get; set; }

        public void New(string configpath, string wq_input_path, int nhru, int nseg, int nreach, DateTime startDate, DateTime endDate, string fertfile)
        {
            int total_days = (endDate - startDate).Days + 1;
            save_nps_ex(configpath, wq_input_path, fertfile);
            save_gwinit_file(wq_input_path, nhru);
            copy_extern_files(configpath, wq_input_path);
            save_sfrwq(configpath, wq_input_path, nseg, nreach);
            save_sfrwq_div(wq_input_path, total_days);
            save_sfrwq_ps(wq_input_path, total_days);
            save_month_cycle(startDate, endDate, wq_input_path);
            save_year_cycle(startDate, endDate, wq_input_path);
        }

        private void save_nps_ex(string configpath, string wq_input_path, string fertfile)
        {
            var npsex = Path.Combine(configpath, "wq\\nps.ex");
            var npsex_out = Path.Combine(wq_input_path, "nps.ex");
            File.Copy(npsex, npsex_out, true);
            //StreamReader sr = new StreamReader(npsex);
            //StreamWriter sw = new StreamWriter(npsex_out);
            //StreamReader sr_fert = new StreamReader(fertfile);
            //string line = "";
            //for (int i = 0; i < 38; i++)
            //{
            //    line = sr.ReadLine();
            //    sw.WriteLine(line);
            //}
            //line = sr_fert.ReadLine();
            //sw.WriteLine(line);

            //var bufs = TypeConverterEx.Split<int>(line);
            //int fert_times = 1;
            //int fert_hru = bufs[1];

            //line = sr_fert.ReadLine();
            //sw.WriteLine(line);
            //line = sr_fert.ReadLine();
            //sw.WriteLine(line);

            //sr.Close();
            //sr_fert.Close();
            //sw.Close();
            var fert_times = 3;
            var fert_hru = 5;
            var fertN = Path.Combine(wq_input_path, "ferti_N.txt");
            StreamWriter sw_fertN = new StreamWriter(fertN);
            var line = string.Format("#fertilizer N file (kg/ha), according to num_fert_count and num_fert_cell in nps.ex. Generated by VHF on {0}", DateTime.Now);
            sw_fertN.WriteLine(line);
            float[] arr = Enumerable.Repeat(FertN, fert_hru).ToArray();
            var arr_str = string.Join(" ", arr);
            for (int i = 0; i < fert_times; i++)
            {
                sw_fertN.WriteLine(arr_str);
            }
            sw_fertN.Close();

            var fertP = Path.Combine(wq_input_path, "ferti_P.txt");
            StreamWriter sw_fertP = new StreamWriter(fertP);
            line = string.Format("#fertilizer P file (kg/ha), according to num_fert_count and num_fert_cell in nps.ex. Generated by VHF on {0}", DateTime.Now);
            sw_fertP.WriteLine(line);
            arr = Enumerable.Repeat(FertP, fert_hru).ToArray();
            arr_str = string.Join(" ", arr);
            for (int i = 0; i < fert_times; i++)
            {
                sw_fertP.WriteLine(arr_str);
            }
            sw_fertP.Close();

        }

        private void save_gwinit_file(string wq_input_path, int nhru)
        {
            var gwinit_file_out = Path.Combine(wq_input_path, "init_gw_extern.txt");
            StreamWriter sw = new StreamWriter(gwinit_file_out);
            float[] arr = Enumerable.Repeat(GW_Init_NO3, nhru).ToArray();
            var arr_str = string.Join(" ", arr);
            sw.WriteLine(arr_str);
            sw.Close();
        }

        private void copy_extern_files(string configpath, string wq_input_path)
        {
            var npsex = Path.Combine(configpath, "wq\\init_nps_extern.txt");
            var npsex_out = Path.Combine(wq_input_path, "init_nps_extern.txt");
            File.Copy(npsex, npsex_out, true);

            npsex = Path.Combine(configpath, "wq\\init_otherwq_extern.txt");
            npsex_out = Path.Combine(wq_input_path, "init_otherwq_extern.txt");
            File.Copy(npsex, npsex_out, true);

            npsex = Path.Combine(configpath, "wq\\init_gw_otherwq_extern.txt");
            npsex_out = Path.Combine(wq_input_path, "init_gw_otherwq_extern.txt");
            File.Copy(npsex, npsex_out, true);

        }

        private void save_sfrwq(string configpath, string wq_input_path, int nseg, int nreach)
        {
            StreamReader sr = new StreamReader(Path.Combine(configpath, "wq\\sfrwq.ex"));
            StreamWriter sw = new StreamWriter(Path.Combine(wq_input_path, "sfrwq.ex"));
            var line = sr.ReadLine();
            var newline = string.Format("9 {0} {1}	1	5 # npolut, numreach, numseg, output_polut_index1,output_polut_index2", nseg, nreach);
            sw.WriteLine(newline);
            while (!sr.EndOfStream)
            {
                line = sr.ReadLine();
                sw.WriteLine(line);
            }

            sr.Close();
            sw.Close();
        }

        private void save_sfrwq_div(string wq_input_path, int total_days)
        {
            StreamWriter sw = new StreamWriter(Path.Combine(wq_input_path, "sfrwq_div.ex"));
            sw.WriteLine("1 2 # num_sfr_div, ts_flag(1: constant; 2: time-varient)");
            sw.WriteLine("1 1 1 # iseg ireach reach_serial_id");
            sw.WriteLine("0 1 # time_step data_flag");
            sw.WriteLine("0 # div_q");
            for (int i = 1; i <= total_days; i++)
            {
                sw.WriteLine( string.Format( "{0} {1} # time_step data_flag", i, -1));
            }
            sw.Close();
        }

        private void save_sfrwq_ps(string wq_input_path, int total_days)
        {
            StreamWriter sw = new StreamWriter(Path.Combine(wq_input_path, "sfrwq_ps.ex"));
            sw.WriteLine("1 2 # num_nps, ts_flag(1: constant; 2: time-varient)");
            sw.WriteLine("1 1 1 # iseg ireach reach_serial_id");
            sw.WriteLine("0 1 # time_step data_flag");
            sw.WriteLine("0 0 0 0 0 0 0 0 0 # ps_q, NO3 ON P OP Sendiment chla CBOD DO NH3");
            for (int i = 1; i <= total_days; i++)
            {
                sw.WriteLine(string.Format("{0} {1} # time_step data_flag", i, -1));
            }
            sw.Close();
        }

        private void save_month_cycle(DateTime startDate, DateTime endDate, string wq_input_path)
        {
            string outputPath = Path.Combine(wq_input_path, "month_cycle.txt");
            if (endDate < startDate)
                throw new ArgumentException("endDate must be greater than or equal to startDate");

            var lines = new List<string>
            {
                "#month_cycle: used for the output of monthly result"
            };

            int totalMonths = 0;
            int maxDaysInMonth = 31;

            DateTime current = new DateTime(startDate.Year, startDate.Month, 1);
            DateTime end = new DateTime(endDate.Year, endDate.Month, 1);

            // 先计算总月数
            while (current <= end)
            {
                totalMonths++;
                current = current.AddMonths(1);
            }

            lines.Add(string.Format("{0} {1} #num_month_cycle len_month_cycle", totalMonths, maxDaysInMonth));

            int dayCounter = 0;
            current = new DateTime(startDate.Year, startDate.Month, 1);

            while (current <= end)
            {
                int year = current.Year;
                int month = current.Month;
                int daysInMonth = DateTime.DaysInMonth(year, month);

                int startDay = dayCounter + 1;
                int endDay = dayCounter + daysInMonth;

                lines.Add(string.Format("{0} {1} 1 {2} {3} {4}", year, month, daysInMonth, startDay, endDay));

                dayCounter += daysInMonth;
                current = current.AddMonths(1);
            }

            File.WriteAllLines(outputPath, lines, Encoding.ASCII);
        }

        public void save_year_cycle(DateTime startDate, DateTime endDate, string wq_input_path)
        {
            string outputPath = Path.Combine(wq_input_path, "year_cycle.txt");
            if (endDate < startDate)
                throw new ArgumentException("endDate must be greater than or equal to startDate");

            var lines = new List<string>
            {
                "#year_cycle: used for the calculation of daily solar irradiation"
            };

            int yearCount = 0;
            int maxDaysInYear = 366;

            DateTime current = new DateTime(startDate.Year, 1, 1);
            DateTime endYear = new DateTime(endDate.Year, 1, 1);

            // 计算总年数
            while (current <= endYear)
            {
                yearCount++;
                current = current.AddYears(1);
            }

            lines.Add(string.Format("{0} {1} # num_year_cycle len_year_cycle", yearCount, maxDaysInYear));

            int dayCounter = 0;
            current = new DateTime(startDate.Year, 1, 1);

            while (current <= endYear)
            {
                int year = current.Year;
                bool isLeap = DateTime.IsLeapYear(year);
                int daysInYear = isLeap ? 366 : 365;

                int startDay = dayCounter + 1;
                int endDay = dayCounter + daysInYear;

                lines.Add(string.Format("{0} 1 {1} {2} {3}", year, daysInYear, startDay, endDay));

                dayCounter += daysInYear;
                current = current.AddYears(1);
            }

            File.WriteAllLines(outputPath, lines, Encoding.ASCII);
        }

    }
}
