// THIS FILE IS PART OF Visual HEIFLOW
// THIS PROGRAM IS NOT FREE SOFTWARE. 
// Copyright (c) 2015-2017 Yong Tian, SUSTech, Shenzhen, China. All rights reserved.
// Email: tiany@sustc.edu.cn
// Web: http://ese.sustc.edu.cn/homepage/index.aspx?lid=100000005794726
using DotSpatial.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Heiflow.Core.Data;
using System.IO;
using Heiflow.Models.Generic;
using System.ComponentModel;
using Heiflow.Controls.WinForm.Editors;
using System.Windows.Forms.Design;
using GeoAPI.Geometries;
using Heiflow.Applications;
using Heiflow.Controls.WinForm.Toolbox;
using Heiflow.Models.Tools;
using Heiflow.Presentation.Services;

namespace Heiflow.Tools.Conversion
{
    public class SaveAsClimateInput : ModelTool
    {
        public SaveAsClimateInput()
        {
            Name = "Save As Climate Input";
            Category = "Driving Forces";
            Description = "Save data cube as climate input data file";
            Version = "1.0.0.0";
            this.Author = "Yong Tian";
            VariableName = "variable";
            CellCount = 1;
            Format = "0.00";
        }

        [Category("Input")]
        [Description("The name of the input matrix")]
        public string Source { get; set; }

        [Category("Input")]
        [Description("The name of the variable")]
        public string VariableName { get; set; }

        [Category("Input")]
        [Description("The number of cell count")]
        public int CellCount { get; set; }

        [Category("Optional")]
        [Description("The numeric format, e.g. 0.000")]
        public string Format { get; set; }

        [Category("Output")]
        [Description("The file folder directory for the input raster")]
        [EditorAttribute(typeof(SaveFileNameEditor), typeof(System.Drawing.Design.UITypeEditor))]
        public string DataFileName
        {
            get;
            set;
        }


        public override void Initialize()
        {
            this.Initialized = Validate(Source);
        }

        public override bool Execute(DotSpatial.Data.ICancelProgressHandler cancelProgressHandler)
        {
            var var_index = 0;
            var mat = Get3DMat(Source, ref var_index);
            int progress = 0;
            int count = 1;
            if (mat.DateTimes != null)
            {
                int nstep = mat.Size[1];
                int ncell = mat.Size[2];
                StreamWriter sw = new StreamWriter(DataFileName);
                string line = "Metrological File, generated by the software written by Visual Heiflow at " + DateTime.Now.ToString();
                sw.WriteLine(line);

                if (CellCount != ncell && ncell == 1)
                {
                    line = VariableName + " " + CellCount;
                    sw.WriteLine(line);
                    sw.WriteLine("######################");
                    for (int t = 0; t < nstep; t++)
                    {
                        var date = mat.DateTimes[t];
                        var scalar = mat.Value[var_index][t][0];
                        line = string.Format("{0}\t{1}\t{2}\t{3}\t{4}\t{5}\t", date.Year, date.Month, date.Day, date.Hour, date.Minute, date.Second);

                        for (int i = 0; i < CellCount; i++)
                        {
                            line += scalar.ToString(Format) + "\t";
                        }
                        line += scalar.ToString(Format);
                        sw.WriteLine(line);
                        progress = t * 100 / nstep;
                        if (progress > count)
                        {
                            cancelProgressHandler.Progress("Package_Tool", progress, "Processing step:" + t);
                            count++;
                        }
                    }
                }
                else
                {
                    line = VariableName + " " + ncell;
                    sw.WriteLine(line);
                    sw.WriteLine("######################");
                    for (int t = 0; t < nstep; t++)
                    {
                        var date = mat.DateTimes[t];
                        var vec = mat.Value[var_index][t];
                        line = string.Format("{0}\t{1}\t{2}\t{3}\t{4}\t{5}\t", date.Year, date.Month, date.Day, date.Hour, date.Minute, date.Second);

                        for (int i = 0; i < vec.Length - 1; i++)
                        {
                            line += vec[i].ToString(Format) + "\t";
                        }
                        line += vec[vec.Length - 1];
                        sw.WriteLine(line);
                        progress = t * 100 / nstep;
                        if (progress > count)
                        {
                            cancelProgressHandler.Progress("Package_Tool", progress, "Processing step:" + t);
                            count++;
                        }
                    }
                }
          
                sw.Close();
                return true;
            }
            else
            {
                cancelProgressHandler.Progress("Package_Tool", 100, "the input data cube does not contain date information");
                return false;
            }

        }
    }
}