//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUST.WREIS.Dot3D.Display.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_en_US() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HUST.WREIS.Dot3D.Display.Properties.Resource-en-US", typeof(Resource_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add hot point 的本地化字符串。
        /// </summary>
        internal static string AddHotPt {
            get {
                return ResourceManager.GetString("AddHotPt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Area 的本地化字符串。
        /// </summary>
        internal static string AreaChart {
            get {
                return ResourceManager.GetString("AreaChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bar 的本地化字符串。
        /// </summary>
        internal static string BarChart {
            get {
                return ResourceManager.GetString("BarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cell Index: 的本地化字符串。
        /// </summary>
        internal static string CellIndex {
            get {
                return ResourceManager.GetString("CellIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cell Value: 的本地化字符串。
        /// </summary>
        internal static string CellValue {
            get {
                return ResourceManager.GetString("CellValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property... 的本地化字符串。
        /// </summary>
        internal static string ChartProp {
            get {
                return ResourceManager.GetString("ChartProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chart Type 的本地化字符串。
        /// </summary>
        internal static string ChartType {
            get {
                return ResourceManager.GetString("ChartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string ClcSelectionCell {
            get {
                return ResourceManager.GetString("ClcSelectionCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string ClearColProfile {
            get {
                return ResourceManager.GetString("ClearColProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear hot point 的本地化字符串。
        /// </summary>
        internal static string ClearHotPt {
            get {
                return ResourceManager.GetString("ClearHotPt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete hot point 的本地化字符串。
        /// </summary>
        internal static string DelHotPt {
            get {
                return ResourceManager.GetString("DelHotPt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Data... 的本地化字符串。
        /// </summary>
        internal static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filled Line 的本地化字符串。
        /// </summary>
        internal static string FilledLine {
            get {
                return ResourceManager.GetString("FilledLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide 的本地化字符串。
        /// </summary>
        internal static string HideSelectionCell {
            get {
                return ResourceManager.GetString("HideSelectionCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open... 的本地化字符串。
        /// </summary>
        internal static string ImportData {
            get {
                return ResourceManager.GetString("ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lengend 的本地化字符串。
        /// </summary>
        internal static string Lengend {
            get {
                return ResourceManager.GetString("Lengend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line 的本地化字符串。
        /// </summary>
        internal static string LineChart {
            get {
                return ResourceManager.GetString("LineChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Longitude: {0:f4}    Latitude: {1:f4}    Elevation: {2}m    Heading: {3:f2}                                     Altitude: {4} 的本地化字符串。
        /// </summary>
        internal static string PosInfo {
            get {
                return ResourceManager.GetString("PosInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selection Features 的本地化字符串。
        /// </summary>
        internal static string SelectionCell {
            get {
                return ResourceManager.GetString("SelectionCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active Time Series 的本地化字符串。
        /// </summary>
        internal static string ViewActiveTimeSeries {
            get {
                return ResourceManager.GetString("ViewActiveTimeSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Layers 的本地化字符串。
        /// </summary>
        internal static string ViewAllLayerVal {
            get {
                return ResourceManager.GetString("ViewAllLayerVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Averaged 的本地化字符串。
        /// </summary>
        internal static string ViewAvLayerVal {
            get {
                return ResourceManager.GetString("ViewAvLayerVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Probe Cell Value 的本地化字符串。
        /// </summary>
        internal static string ViewCellVal {
            get {
                return ResourceManager.GetString("ViewCellVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Profile 的本地化字符串。
        /// </summary>
        internal static string ViewColProfile {
            get {
                return ResourceManager.GetString("ViewColProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Layer 的本地化字符串。
        /// </summary>
        internal static string ViewCurrentLayerVal {
            get {
                return ResourceManager.GetString("ViewCurrentLayerVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Data... 的本地化字符串。
        /// </summary>
        internal static string ViewData {
            get {
                return ResourceManager.GetString("ViewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Histogram 的本地化字符串。
        /// </summary>
        internal static string ViewHistLayerVal {
            get {
                return ResourceManager.GetString("ViewHistLayerVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Profile 的本地化字符串。
        /// </summary>
        internal static string ViewProfile {
            get {
                return ResourceManager.GetString("ViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row Profile 的本地化字符串。
        /// </summary>
        internal static string ViewRowProfile {
            get {
                return ResourceManager.GetString("ViewRowProfile", resourceCulture);
            }
        }
    }
}
