//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUST.WREIS.Dot3D.Display.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HUST.WREIS.Dot3D.Display.Properties.Resource-zh-CN", typeof(Resource_zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加热点 的本地化字符串。
        /// </summary>
        internal static string addhotp {
            get {
                return ResourceManager.GetString("addhotp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 面积图 的本地化字符串。
        /// </summary>
        internal static string AreaChart {
            get {
                return ResourceManager.GetString("AreaChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 柱状图 的本地化字符串。
        /// </summary>
        internal static string BarChart {
            get {
                return ResourceManager.GetString("BarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网格索引: 的本地化字符串。
        /// </summary>
        internal static string CellIndex {
            get {
                return ResourceManager.GetString("CellIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    网格值: 的本地化字符串。
        /// </summary>
        internal static string CellValue {
            get {
                return ResourceManager.GetString("CellValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        internal static string ChartProp {
            get {
                return ResourceManager.GetString("ChartProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图表类型 的本地化字符串。
        /// </summary>
        internal static string ChartType {
            get {
                return ResourceManager.GetString("ChartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除热点 的本地化字符串。
        /// </summary>
        internal static string clchotp {
            get {
                return ResourceManager.GetString("clchotp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        internal static string clcSelectionCell {
            get {
                return ResourceManager.GetString("clcSelectionCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        internal static string clearColProfile {
            get {
                return ResourceManager.GetString("clearColProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除热点 的本地化字符串。
        /// </summary>
        internal static string delhotp {
            get {
                return ResourceManager.GetString("delhotp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出数据... 的本地化字符串。
        /// </summary>
        internal static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填充线图 的本地化字符串。
        /// </summary>
        internal static string FilledLine {
            get {
                return ResourceManager.GetString("FilledLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏 的本地化字符串。
        /// </summary>
        internal static string hideSelectionCell {
            get {
                return ResourceManager.GetString("hideSelectionCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入数据... 的本地化字符串。
        /// </summary>
        internal static string ImportData {
            get {
                return ResourceManager.GetString("ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图例 的本地化字符串。
        /// </summary>
        internal static string Lengend {
            get {
                return ResourceManager.GetString("Lengend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 折线图 的本地化字符串。
        /// </summary>
        internal static string LineChart {
            get {
                return ResourceManager.GetString("LineChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经度: {0:f4}    纬度: {1:f4}    海拔: {2}m    方向: {3:f2}                                     视角海拔高度: {4} 的本地化字符串。
        /// </summary>
        internal static string PosInfo {
            get {
                return ResourceManager.GetString("PosInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择要素 的本地化字符串。
        /// </summary>
        internal static string selectionCell {
            get {
                return ResourceManager.GetString("selectionCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有层 的本地化字符串。
        /// </summary>
        internal static string viewAllLayerVal {
            get {
                return ResourceManager.GetString("viewAllLayerVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均 的本地化字符串。
        /// </summary>
        internal static string viewAvLayerVal {
            get {
                return ResourceManager.GetString("viewAvLayerVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看网格值 的本地化字符串。
        /// </summary>
        internal static string viewCellVal {
            get {
                return ResourceManager.GetString("viewCellVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前列 的本地化字符串。
        /// </summary>
        internal static string viewColProfile {
            get {
                return ResourceManager.GetString("viewColProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前层 的本地化字符串。
        /// </summary>
        internal static string viewCurrentLayerVal {
            get {
                return ResourceManager.GetString("viewCurrentLayerVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看数据... 的本地化字符串。
        /// </summary>
        internal static string ViewData {
            get {
                return ResourceManager.GetString("ViewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直方图 的本地化字符串。
        /// </summary>
        internal static string viewHistLayerVal {
            get {
                return ResourceManager.GetString("viewHistLayerVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看立体剖面 的本地化字符串。
        /// </summary>
        internal static string viewProfile {
            get {
                return ResourceManager.GetString("viewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前行 的本地化字符串。
        /// </summary>
        internal static string viewRowProfile {
            get {
                return ResourceManager.GetString("viewRowProfile", resourceCulture);
            }
        }
    }
}
