//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heiflow.Controls.WinForm {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SymbologyFormsMessageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SymbologyFormsMessageStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heiflow.Controls.WinForm.SymbologyFormsMessageStrings", typeof(SymbologyFormsMessageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Factorial value should be grater than 0 的本地化字符串。
        /// </summary>
        internal static string AttributeCalculator_FactGreaterThanZero {
            get {
                return ResourceManager.GetString("AttributeCalculator_FactGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The destination field data type is incompatible (double or string or integer) 的本地化字符串。
        /// </summary>
        internal static string AttributeCalculator_IncompatibleDestinationField {
            get {
                return ResourceManager.GetString("AttributeCalculator_IncompatibleDestinationField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The function name was not recognized as one of the standard function names. 的本地化字符串。
        /// </summary>
        internal static string AttributeCalculator_NonStandardFunction {
            get {
                return ResourceManager.GetString("AttributeCalculator_NonStandardFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter is invalid 的本地化字符串。
        /// </summary>
        internal static string AttributeCalculator_ParameterInvalid {
            get {
                return ResourceManager.GetString("AttributeCalculator_ParameterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The root n-th root is incorrect 的本地化字符串。
        /// </summary>
        internal static string AttributeCalculator_RootNthRootIncorrect {
            get {
                return ResourceManager.GetString("AttributeCalculator_RootNthRootIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There were too many closing brackets in the string expression. 的本地化字符串。
        /// </summary>
        internal static string AttributeCalculator_TooManyClosingBrackets {
            get {
                return ResourceManager.GetString("AttributeCalculator_TooManyClosingBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value entered could not be correctly parsed into a valid double precision floating point value. 的本地化字符串。
        /// </summary>
        internal static string DoubleBox_DoubleError {
            get {
                return ResourceManager.GetString("DoubleBox_DoubleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a double precision floating point value. 的本地化字符串。
        /// </summary>
        internal static string DoubleBox_DoubleHelp {
            get {
                return ResourceManager.GetString("DoubleBox_DoubleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Features 的本地化字符串。
        /// </summary>
        internal static string ExportFeature_FeaturesAll {
            get {
                return ResourceManager.GetString("ExportFeature_FeaturesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Features in View Extent 的本地化字符串。
        /// </summary>
        internal static string ExportFeature_FeaturesExtent {
            get {
                return ResourceManager.GetString("ExportFeature_FeaturesExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected features 的本地化字符串。
        /// </summary>
        internal static string ExportFeature_FeaturesSelected {
            get {
                return ResourceManager.GetString("ExportFeature_FeaturesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In order to specify a custom filter expression, the custom mode must be selected first. 的本地化字符串。
        /// </summary>
        internal static string FeatureCategoryControl_CustomOnly {
            get {
                return ResourceManager.GetString("FeatureCategoryControl_CustomOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Each symbol group can define a separate string expression that includes attribute values.  Double click fields to add it to the expression. 的本地化字符串。
        /// </summary>
        internal static string LabelSetup_Help1 {
            get {
                return ResourceManager.GetString("LabelSetup_Help1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use the Members tab to design a filter expression that restricts which features will be assigned to a specific label. 的本地化字符串。
        /// </summary>
        internal static string LabelSetup_Help2 {
            get {
                return ResourceManager.GetString("LabelSetup_Help2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use the Expression Tab to design the text that should appear in a label.  Fields indicated with brackets will be substituted with real values. 的本地化字符串。
        /// </summary>
        internal static string LabelSetup_Help3 {
            get {
                return ResourceManager.GetString("LabelSetup_Help3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Each group can specify its own basic design characteristics. 的本地化字符串。
        /// </summary>
        internal static string LabelSetup_Help4 {
            get {
                return ResourceManager.GetString("LabelSetup_Help4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Each group can specify its advanced characteristics. 的本地化字符串。
        /// </summary>
        internal static string LabelSetup_Help5 {
            get {
                return ResourceManager.GetString("LabelSetup_Help5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This feature is not yet supported for tables with more than 50, 000 rows. 的本地化字符串。
        /// </summary>
        internal static string LargeEditsNotSupported {
            get {
                return ResourceManager.GetString("LargeEditsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_Confirm {
            get {
                return ResourceManager.GetString("TableEditorControl_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not copy FID 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_CopyFid_Could_not_copy_FID {
            get {
                return ResourceManager.GetString("TableEditorControl_CopyFid_Could_not_copy_FID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find the field in the attribute Table colums 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_CopyFid_Couldnt_find_field {
            get {
                return ResourceManager.GetString("TableEditorControl_CopyFid_Couldnt_find_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not execute the query. 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_CouldNotExecuteQuery {
            get {
                return ResourceManager.GetString("TableEditorControl_CouldNotExecuteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find or replace items. 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_CouldNotFindReplace {
            get {
                return ResourceManager.GetString("TableEditorControl_CouldNotFindReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  of  的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_DisplaySelectedRowNumberLable__of_ {
            get {
                return ResourceManager.GetString("TableEditorControl_DisplaySelectedRowNumberLable__of_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Selected 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_DisplaySelectedRowNumberLable__Selected {
            get {
                return ResourceManager.GetString("TableEditorControl_DisplaySelectedRowNumberLable__Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter Find String 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_EnterFindString {
            get {
                return ResourceManager.GetString("TableEditorControl_EnterFindString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shapefiles (*.shp) |*.shp 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_exportSelectedFeaturesToolStripMenuItem_Click_Shapefiles____shp_____SHP {
            get {
                return ResourceManager.GetString("TableEditorControl_exportSelectedFeaturesToolStripMenuItem_Click_Shapefiles____sh" +
                        "p_____SHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not import column fields. 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_FieldImportFailed {
            get {
                return ResourceManager.GetString("TableEditorControl_FieldImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_Find {
            get {
                return ResourceManager.GetString("TableEditorControl_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not import column fields 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_ImportFieldsFromDbf_Could_not_import_column_fields {
            get {
                return ResourceManager.GetString("TableEditorControl_ImportFieldsFromDbf_Could_not_import_column_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DBase Files (*.dbf)|*.dbf 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_ImportFieldsFromDbf_DBase_Files____dbf____DBF {
            get {
                return ResourceManager.GetString("TableEditorControl_ImportFieldsFromDbf_DBase_Files____dbf____DBF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not create new field 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_NewFieldFail {
            get {
                return ResourceManager.GetString("TableEditorControl_NewFieldFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None of the rows contain a value that matches the specified value. 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_NoMatch {
            get {
                return ResourceManager.GetString("TableEditorControl_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to remove the fields? 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_RemoveFields {
            get {
                return ResourceManager.GetString("TableEditorControl_RemoveFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column edits are not yet supported for datasets with more than 50, 000 attributes 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_removeFieldToolStripMenuItem_Click_Column_edits_are_not_yet_supported_for_datasets_with_more_than_50_000_attributes {
            get {
                return ResourceManager.GetString("TableEditorControl_removeFieldToolStripMenuItem_Click_Column_edits_are_not_yet_su" +
                        "pported_for_datasets_with_more_than_50_000_attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This feature is not yet supported for datasets with larger than 50, 000 rows. 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_renameFieldToolStripMenuItem_Click_This_feature_is_not_yet_supported_for_datasets_with_larger_than_50_000_rows_ {
            get {
                return ResourceManager.GetString("TableEditorControl_renameFieldToolStripMenuItem_Click_This_feature_is_not_yet_sup" +
                        "ported_for_datasets_with_larger_than_50_000_rows_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unfamilar data type to replace 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_ReplaceString_Unfamilar_data_type_to_replace {
            get {
                return ResourceManager.GetString("TableEditorControl_ReplaceString_Unfamilar_data_type_to_replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 row 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_Row {
            get {
                return ResourceManager.GetString("TableEditorControl_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 rows 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_RowPlural {
            get {
                return ResourceManager.GetString("TableEditorControl_RowPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to save edits.  的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_SaveEdits_Unable_to_save_edits__ {
            get {
                return ResourceManager.GetString("TableEditorControl_SaveEdits_Unable_to_save_edits__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 s 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_SelectedRowCountPluralization {
            get {
                return ResourceManager.GetString("TableEditorControl_SelectedRowCountPluralization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} of {1} selected. 的本地化字符串。
        /// </summary>
        internal static string TableEditorControl_SelectedRowCountStringFormat {
            get {
                return ResourceManager.GetString("TableEditorControl_SelectedRowCountStringFormat", resourceCulture);
            }
        }
    }
}
